# Generated by Django 4.1.7 on 2023-05-03 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=100, null=True)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=100, null=True)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statename', models.CharField(max_length=100, null=True)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
                ('postingdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertytitle', models.CharField(max_length=100, null=True)),
                ('propertydescription', models.CharField(max_length=300, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('bedrooms', models.CharField(max_length=100, null=True)),
                ('bathrooms', models.CharField(max_length=100, null=True)),
                ('floors', models.CharField(max_length=100, null=True)),
                ('garages', models.CharField(max_length=100, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=100, null=True)),
                ('rentorsaleprice', models.CharField(max_length=100, null=True)),
                ('beforepricelabel', models.CharField(max_length=100, null=True)),
                ('afterpricelabel', models.CharField(max_length=100, null=True)),
                ('propertyid', models.CharField(max_length=100, null=True)),
                ('centercooling', models.CharField(max_length=100, null=True)),
                ('balcony', models.CharField(max_length=100, null=True)),
                ('petfriendly', models.CharField(max_length=100, null=True)),
                ('barbeque', models.CharField(max_length=100, null=True)),
                ('firealarm', models.CharField(max_length=100, null=True)),
                ('modernkitchen', models.CharField(max_length=100, null=True)),
                ('storage', models.CharField(max_length=100, null=True)),
                ('dryer', models.CharField(max_length=100, null=True)),
                ('heating', models.CharField(max_length=100, null=True)),
                ('pool', models.CharField(max_length=100, null=True)),
                ('laundry', models.CharField(max_length=100, null=True)),
                ('sauna', models.CharField(max_length=100, null=True)),
                ('gym', models.CharField(max_length=100, null=True)),
                ('elevator', models.CharField(max_length=100, null=True)),
                ('dishwasher', models.CharField(max_length=100, null=True)),
                ('emergencyexit', models.CharField(max_length=100, null=True)),
                ('featuredimage', models.FileField(blank=True, null=True, upload_to='')),
                ('galleryimage1', models.FileField(blank=True, null=True, upload_to='')),
                ('galleryimage2', models.FileField(blank=True, null=True, upload_to='')),
                ('galleryimage3', models.FileField(blank=True, null=True, upload_to='')),
                ('galleryimage4', models.FileField(blank=True, null=True, upload_to='')),
                ('galleryimage5', models.FileField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(max_length=300, null=True)),
                ('zipcode', models.CharField(max_length=30, null=True)),
                ('neighborhood', models.CharField(max_length=200, null=True)),
                ('listingdate', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.city')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.propertytype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userremark', models.CharField(max_length=500, null=True)),
                ('postingdate', models.DateTimeField(auto_now_add=True)),
                ('ispublish', models.CharField(max_length=50, null=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estate.property')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estate.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('emailid', models.CharField(max_length=100, null=True)),
                ('mobileno', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
                ('enquiryno', models.CharField(max_length=50, null=True)),
                ('enquirydate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('remark', models.CharField(max_length=500, null=True)),
                ('remarkdate', models.DateField(null=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estate.property')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estate.state'),
        ),
    ]
